version: '3.5'
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: mdillon/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - gpao-network
  api-gpao:
    build:
      context: ./
      dockerfile: docker/api/Dockerfile
    container_name: api-gpao
    hostname: api-gpao
    image: api-gpao
    restart: always
    environment:
     - SERVER=${SERVER}
    env_file:
     - docker/api.env
    depends_on:
      - postgres
    ports:
      - 8080:8080
    networks:
      - gpao-network
  monitor-gpao:
    build:
      context: ./
      dockerfile: docker/monitor/Dockerfile
    container_name: monitor-gpao
    hostname: monitor-gpao
    image: monitor-gpao
    restart: always
    environment:
     - SERVER=${SERVER}
    env_file:
      - docker/monitor.env
    depends_on:
      - api-gpao
    ports:
      - 8000:8000
    networks:
      - gpao-network
  client-gpao:
    build:
      context: ./
      dockerfile: docker/client/Dockerfile
    image: client-gpao
    container_name: client-gpao
    hostname: client-gpao
    restart: always
    environment:
      - URL_API=api-gpao
    entrypoint: ["python", "client.py"]
    depends_on:
      - api-gpao
    networks:
      - gpao-network
volumes:
  postgres-data:
networks:
  gpao-network:
    name: gpao-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/16
